# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: false

addons:
  apt:
    packages:
       - unixodbc-dev
       - libarchive-dev

r_github_packages:
 - ajdamico/lodown

env:
 - this_sample_break=1
 - this_sample_break=2
 - this_sample_break=3
 - this_sample_break=4
 - this_sample_break=5
matrix:
    fast_finish: true
